# Generated by Django 5.2 on 2025-04-16 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudManager', '0004_customuser_join_date_customuser_last_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ADD_INCOME', 'Add Income')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
