# Generated by Django 5.2 on 2025-04-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudManager', '0005_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Priyesh', max_length=100),
            preserve_default=False,
        ),
    ]
