# Generated by Django 5.2 on 2025-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudManager', '0006_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='India'),
        ),
    ]
