# Generated by Django 5.2 on 2025-05-02 05:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudManager', '0008_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Account number must contain only digits.')])),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Invalid IFSC code format.')])),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$', 'Invalid UPI ID format.')])),
                ('card_number', models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Card number must be exactly 16 digits.')])),
                ('name_on_card', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^(0[1-9]|1[0-2])\\/\\d{2}$', 'Expiry date must be in MM/YY format.')])),
                ('cvv', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', 'CVV must be 3 or 4 digits.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
