# Generated by Django 5.2 on 2025-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudManager', '0010_monthlyincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], default='InActive', max_length=10, verbose_name='Account Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activation Date'),
        ),
    ]
