# Generated by Django 5.2 on 2025-05-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudManager', '0012_paymentscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('Failed', 'Failed')], default='Completed', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=10),
        ),
    ]
